### PR TITLE
25 fix tutorial

### LINKED ISSUE #25: [BUG] The tutorial does not work
# Description

- Executing the REST query from the tutorial produces the following error:

```
[16:28:59.143640] [E] [thread 22] [StacktraceLoader.cpp:33] [collectAndPrintStacktrace] Stacktrace:
 Stack trace (most recent call last) in thread 22:
#31   Object "/usr/lib/aarch64-linux-gnu/ld-linux-aarch64.so.1", at 0xffffffffffffffff, in 
#30   Object "/usr/lib/aarch64-linux-gnu/libc.so.6", at 0xffff7bee5edb, in 
#29   Object "/usr/lib/aarch64-linux-gnu/libc.so.6", at 0xffff7be7d5c7, in 
#28   Object "/usr/local/lib/libnes-worker.so", at 0xffff84a5e98f, in 
#27   Object "/usr/local/lib/libnes-worker.so", at 0xffff847e7967, in grpc::ThreadManager::WorkerThread::Run()
#26   Object "/usr/local/lib/libnes-worker.so", at 0xffff847e7777, in grpc::ThreadManager::MainWorkLoop()
#25   Object "/usr/local/lib/libnes-worker.so", at 0xffff847dfdaf, in grpc::Server::SyncRequest::ContinueRunAfterInterception()
#24   Object "/usr/local/lib/libnes-grpc.so", at 0xffff7c51ebef, in grpc::internal::RpcMethodHandler<WorkerRPCService::Service, RegisterQueryRequest, RegisterQueryReply, google::protobuf::MessageLite, google::protobuf::MessageLite>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)
#23   Object "/usr/local/lib/libnes-grpc.so", at 0xffff7c51eebb, in grpc::Status grpc::internal::CatchingFunctionHandler<grpc::internal::RpcMethodHandler<WorkerRPCService::Service, RegisterQueryRequest, RegisterQueryReply, google::protobuf::MessageLite, google::protobuf::MessageLite>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}>(grpc::internal::RpcMethodHandler<WorkerRPCService::Service, RegisterQueryRequest, RegisterQueryReply, google::protobuf::MessageLite, google::protobuf::MessageLite>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}&&)
#22   Object "/usr/local/lib/libnes-worker.so", at 0xffff847a54d3, in NES::WorkerRPCServer::RegisterQuery(grpc::ServerContext*, RegisterQueryRequest const*, RegisterQueryReply*)
#21   Object "/usr/local/lib/libnes-runtime.so", at 0xffff7e0ac367, in NES::Runtime::NodeEngine::registerDecomposableQueryPlan(std::shared_ptr<NES::DecomposedQueryPlan> const&)
#20   Object "/usr/local/lib/libnes-runtime.so", at 0xffff7e0aba3f, in NES::Runtime::NodeEngine::registerExecutableQueryPlan(std::shared_ptr<NES::Runtime::Execution::ExecutableQueryPlan> const&)
#19   Object "/usr/local/lib/libnes-runtime.so", at 0xffff7e0c21eb, in NES::Runtime::AbstractQueryManager::registerQuery(std::shared_ptr<NES::Runtime::Execution::ExecutableQueryPlan> const&)
#18   Object "/usr/local/lib/libnes-runtime.so", at 0xffff7e098ba7, in NES::Runtime::Execution::ExecutableQueryPlan::setup()
#17   Object "/usr/local/lib/libnes-runtime.so", at 0xffff7e090883, in NES::Runtime::Execution::ExecutablePipeline::setup(std::shared_ptr<NES::Runtime::AbstractQueryManager> const&, std::shared_ptr<NES::Runtime::BufferManager> const&)
#16   Object "/usr/local/lib/libnes-execution.so", at 0xffff84356c6b, in NES::Runtime::Execution::CompiledExecutablePipelineStage::setup(NES::Runtime::Execution::PipelineExecutionContext&)
#15   Object "/usr/local/lib/libnes-execution.so", at 0xffff84359003, in std::__basic_future<std::unique_ptr<NES::Nautilus::Backends::Executable, std::default_delete<NES::Nautilus::Backends::Executable> > >::_M_get_result() const
#14   Object "/usr/local/lib/libnes-execution.so", at 0xffff84357443, in 
#13   Object "/usr/lib/aarch64-linux-gnu/libc.so.6", at 0xffff7be825d3, in 
#12   Object "/usr/local/lib/libnes-worker.so", at 0xffff8478cf6b, in std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
#11   Object "/usr/local/lib/libnes-execution.so", at 0xffff843570fb, in 
#10   Object "/usr/local/lib/libnes-execution.so", at 0xffff843565a7, in NES::Runtime::Execution::CompiledExecutablePipelineStage::compilePipeline()
#9    Object "/usr/local/lib/libnes-execution.so", at 0xffff8435558f, in NES::Runtime::Execution::CompiledExecutablePipelineStage::createIR(NES::DumpHelper&, NES::Timer<std::chrono::duration<long, std::ratio<1l, 1000000000l> >, std::ratio<1l, 1000l>, double, std::chrono::_V2::system_clock>&)
#8    Object "/usr/local/lib/libnes-nautilus.so", at 0xffff7f7f081f, in NES::Nautilus::Tracing::TraceContext::apply(std::function<NES::Nautilus::Tracing::ValueRef ()> const&)
#7    Object "/usr/local/lib/libnes-execution.so", at 0xffff84356ef7, in 
#6    Object "/usr/local/lib/libnes-execution.so", at 0xffff843d00cf, in NES::Runtime::Execution::Operators::KeyedSliceMerging::open(NES::Runtime::Execution::ExecutionContext&, NES::Runtime::Execution::RecordBuffer&) const
#5    Object "/usr/local/lib/libnes-execution.so", at 0xffff843d68e3, in NES::Runtime::Execution::Operators::KeyedWindowEmitAction::emitSlice(NES::Runtime::Execution::ExecutionContext&, std::shared_ptr<NES::Runtime::Execution::Operators::ExecutableOperator const>&, NES::Nautilus::Value<NES::Nautilus::UInt64>&, NES::Nautilus::Value<NES::Nautilus::UInt64>&, NES::Nautilus::Value<NES::Nautilus::UInt64>&, NES::Nautilus::Value<NES::Nautilus::MemRef>&) const
#4    Object "/usr/local/lib/libnes-execution.so", at 0xffff844562a7, in NES::Runtime::Execution::Operators::Emit::execute(NES::Runtime::Execution::ExecutionContext&, NES::Nautilus::Record&) const
#3    Object "/usr/local/lib/libnes-execution.so", at 0xffff84351e57, in NES::Runtime::Execution::MemoryProvider::RowMemoryProvider::write(NES::Nautilus::Value<NES::Nautilus::UInt64>&, NES::Nautilus::Value<NES::Nautilus::MemRef>&, NES::Nautilus::Record&) const
#2    Object "/usr/local/lib/libnes-execution.so", at 0xffff843424c7, in NES::Runtime::Execution::MemoryProvider::MemoryProvider::store(std::shared_ptr<NES::PhysicalType> const&, NES::Nautilus::Value<NES::Nautilus::MemRef>&, NES::Nautilus::Value<NES::Nautilus::MemRef>&, NES::Nautilus::Value<NES::Nautilus::Any>&) const
#1    Object "/usr/local/lib/libnes-common.so", at 0xffff7c7d575f, in NES::Exceptions::NotImplementedException::NotImplementedException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::source_location)
#0    Object "/usr/local/lib/libnes-common.so", at 0xffff7c7cb2fb, in NES::collectAndPrintStacktrace[abi:cxx11]()

```

The schema still uses the `CHAR` data type which is no longer supported.

- Executing the Java query also does not work because the main class is wrong in `build.gradle`.

### PR DESCRIPTION
**Pull request by he-sk**
# Description

This PR brings the tutorial in a state that it runs again. Fixes #25.

# Changes

- Replace `CHAR` with `TEXT` in schema to support new query compiler
- Group over `UINT64` because grouping over `TEXT` does not work. See also: https://github.com/nebulastream/nebulastream/issues/4524
- Fix gradle setup

# Verification

Manual tests.

### CODE REVIEW

File: java-client-example/src/main/java/stream/nebula/example/NebulaStreamTutorial.java [hunk 1]
```diff
@@ -25,15 +25,11 @@ public static void main(String[] args) throws RESTException, IOException {
         Query query = nebulaStreamRuntime
                 .readFromSource("wind_turbines")
                 .window(TumblingWindow.of(eventTime("features_properties_updated"), minutes(10)))
-                .byKey("metadata_id")
+                .byKey("features_properties_capacity")
```
Comment (alepping) [inline java-client-example/src/main/java/stream/nebula/example/NebulaStreamTutorial.java:28]: Is it your convention to use snake_case for keys, names of sources, etc. (ad hoc strings used in queries)? I was just wondering because you use camelCase for the code itself.

**Review by alepping — APPROVED** [review]
LGTM, thanks for fixing the tutorial :partying_face:

File: java-client-example/src/main/java/stream/nebula/example/NebulaStreamTutorial.java (hunk 1 above)
Comment (he-sk) [reply java-client-example/src/main/java/stream/nebula/example/NebulaStreamTutorial.java:28]: I took the names from the data generator repository (https://github.com/nebulastream/data-generator), replacing `.` with `_`. I did not think about consistent naming when I did that.

Going forward, the wind turbines example is not very useful (too many columns in the schema, not enough variation in the data to create interesting queries), so at some point in the future I would like to replace it anyway.

**Review by adrianmichalke — APPROVED** [review]
Cool!
